### ISSUE TITLE
No busca por nombre

### ISSUE THREAD

**Issue by fabianwgl** [lgaticaq/hubot-info-rut#10]
Ya no funciona el buscar por nombre|empresa
log:
ERROR StatusCodeError: 301 - 
"<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white"><center><h1>301 Moved Permanently</h1></center><hr>
<center>nginx</center></body>
</html>"

**Comment by lgaticaq** [comment]
Valeria por avisar, voy a fixearlo

**Comment by lgaticaq** [comment]
Corregido en v2.0.3
