### ISSUE TITLE
output muy grande mata a hubot

### ISSUE THREAD

**Issue by juanbrujo** [lgaticaq/hubot-info-rut#4]
veo que por cada resultado hace una publicación y eso está matando al hubot. será posible/mejor juntar todos los resutados y generar 1 sola publicación?

pd. veo que está en coffeescript y no quiero meterme en eso, por eso no lo soluciono yo.

**Comment by lgaticaq** [comment]
Ok a penas pueda lo soluciono :+1:

**Comment by lgaticaq** [comment]
Listoco, se implemento *attachments* para entregar la respuesta de múltiples resultados de forma colapsada
