### ISSUE TITLE
Hay un tema aquí que está reemplazando sólo el primer espacio

### ISSUE THREAD

**Issue by juanbrujo** [lgaticaq/hubot-info-rut#8]
https://github.com/lgaticaq/hubot-info-rut/blob/master/src/script.coffee#L38

![screen shot 2016-11-16 at 1 01 30 pm](https://cloud.githubusercontent.com/assets/362186/20354601/76155df8-abfd-11e6-84e5-99e24d41f5d4.png)

**Comment by juanbrujo** [comment]
Se me ocurre reemplazar: `urlName = name.replace(" ", "%20")` por: `urlName = name.split(' ').join('%20')`

**Comment by lgaticaq** [comment]
Si, eso cambiar el " " en el replace por una expresión regular

**Comment by lgaticaq** [comment]
reo que mejor aun usar `querystring` de node
